
name: Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          
      - uses: Gr1N/setup-poetry@v8
      - run: |

          VERSION=${{ github.ref }}

          poetry --version
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry version ${VERSION:refs/tags/v}
          poetry publish --build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

