
name: QA

on:
  workflow_dispatch:
  push:

permissions:
  contents: read

env:
  FORCE_COLOR: "1" 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: Gr1N/setup-poetry@v8
      - run: poetry install
      - run: poetry run poe test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: Gr1N/setup-poetry@v8
      - run: poetry install
      - run: poetry run poe lint

  security:
    needs: [test, lint]
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Security scan
        uses: anchore/scan-action@v3
        with:
          path: "."
          fail-build: true
          severity-cutoff: high

      - uses: Gr1N/setup-poetry@v8
      - run: poetry install
      - run: poetry run poe bandit
