
name: QA Post Release

on:
  release:
    types: [published]

permissions:
  contents: read

env:
  FORCE_COLOR: "1" 
  PYTHONUNBUFFERED: "1"

jobs:
  run-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: Gr1N/setup-poetry@v8
      - run: pip install diwrappers
      - run: |
          VERSION=${{ github.ref }}
          VERSION=$(echo $VERSION | sed 's/refs\/tags\/v//')
          pip install diwrappers==$VERSION
          python -m examples

