
name: Test

on:
  workflow_dispatch:
  push:

permissions:
  contents: read

env:
  FORCE_COLOR: "1" 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - uses: Gr1N/setup-poetry@v8
      - name: Run pytest
        run: |
          poetry install
          poetry run pytest **/*.py -vvvvv


